/*
 * File: app/model/MedTree.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('transparence.model.MedTree', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.proxy.JsonP',
        'Ext.data.reader.Json',
        'Ext.data.writer.Json',
         'Ext.data.proxy.Ajax' 
    ],


    config: {
        idProperty: 'o_id',
        fields : ['o_id', 'text', 'name', 'libelle', 'description', 'image', 'qtipCfg']

    },
    getName: function(){
    	 var qtipCfg = this.get('qtipCfg'),
         libelle = qtipCfg.libelle;
         return libelle ;
    	}
    
});